"""baseline: capture existing schema

Revision ID: 882230eb20f7
Revises: 
Create Date: 2026-03-04 15:11:35.431194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882230eb20f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_api_event_id'), ['api_event_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_api_event_id'))

    # ### end Alembic commands ###
